### ISSUE TITLE
Localization Camera views

### ISSUE THREAD

**Issue by joostvanhassel** [shazron/phonegap-questions#1]
Several of the camera views are not localizable.

When taking a picture:
- 'cancel'-button
- flash-settings button

After taking a picture:
- 'Preview'-text
- ''retake'-button
- 'use'-button

Would it be possible to add these strings to the Resource/xx.lproj files?

**Comment by shazron** [comment]
Thanks joostvanhassel - I think these are localized by iOS itself since they are part of iOS. I did some testing already where for example, in the Twitter iOS app, the localized versions do show up if you change to the French language for example. You'll have to enable a language in your iOS app project to see the localized versions when you do a language change.

**Comment by shazron** [comment]
See: http://stackoverflow.com/questions/8258391/how-do-i-localize-uiimagepickercontroller

**Comment by joostvanhassel** [comment]
Tried it immediately and it worked as soon as I added the nl.lproj (for Dutch) folder to Xcode. Thanks for sticking with me on this!
