### ISSUE TITLE
Plugins

### ISSUE THREAD

**Issue by jamesal4** [shazron/phonegap-questions#21]
I'll stick with the Echo example. Let's say that in my js folder I have a file called echo.js that I want  to call the echo method created in my Echo.h and .m file. Which config.xml file do I need to add my plugin to? The universal config.xml, the ios-specific config.xml, or both? I'm currently using cordova 2.9. Which tags and values do I need to create? The docs are not very clear. Thanks for any help.

More things to make my confusion clear.  In the upgrading plugins section of the documentation (https://github.com/apache/cordova-ios/blob/master/guides/Cordova%20Plugin%20Upgrade%20Guide.md), it says that the plugins tag is deprecated, yet here (https://github.com/apache/cordova-docs/blob/master/docs/en/2.9.0/guide/plugin-development/ios/index.md), it says to add plugins under the plugins tag. Should I just give up with this one and move to 3.0? If so, can you point me somewhere that clearly explains how to develop my own plugin? An example project using one would be nice.

**Comment by shazron** [comment]
To be clear, the CLI way is only supported for 3.0 based projects, where you allow the CLI to manage your project. For that case, the universal config.xml would suffice.

Use the feature tag for 2.9 and up, so you won't need to change it again, since in 3.0 only the feature tag is supported.

I'm not sure about the last part - do you have specifics that are not covered by the iOS Plugin Development Guide?
