### ISSUE TITLE
iOS Cordova 3.0 RequireJS and 1st Party Plugins (device, file, logger, etc.)

### ISSUE THREAD

**Issue by njtman** [shazron/phonegap-questions#24]
I just recently downloaded Cordova 3.0 and began playing around with it.  I am a previous user of Cordova 2.0+, and have been using 3rd party plugins successfully with RequireJS as well as 1st party plugins (before they were plugins) such as logger, device, and file. 

In Cordova 3.0, these "1st party" plugins are removed from the cordova.js file and instead included separately in a folder called plugins after they are installed using nodejs.  These files are also referenced in cordova_plugins.js.  

My question is: How can I utilize Cordova 3.0 first party plugins with RequireJS using r.js to combine, minify, and uglify all the files so it creates one large js file. I already know how to use all these libraries to accomplish this and used them fine in Cordova 2.0+, I just need to know how to use RequireJS in conjunction with the new first party plugins and cordova_plugins.js.

Thank you

**Comment by shazron** [comment]
Because of the way the plugins are loaded and installed (cordova_plugins.js) I don't think this is possible. If you look at each core plugin's plugin.xml js-module tag, when loaded the plugin modules are usually attached to the window object globally.

To accomplish what you want, you would have to have to download the plugins locally, and have your own plugin.xml that copies the .js using the <asset> tag http://cordova.apache.org/docs/en/3.0.0/plugin_ref_spec.md

Please also address your concerns by filing an issue against the CLI/Plugman in the Apache JIRA issue tracker, so the team involved in the CLI can take a look at this and perhaps give better advice: http://issues.cordova.io

**Comment by dsshap** [comment]
@njtman were you able to minify all the cordova_plugins and place them in the same js file? If so, can you share your method as well as what you did to the cordova_plugins.js file to instruct it to no not pull the same file multiple time from the server?

**Comment by njtman** [comment]
@dsshap I was never able to resolve this problem.  Based on what shazron mentioned, it seems like it may not be possible (at least easily) to do what I want.

**Comment by dotnetwise** [comment]
Still no one succeeded this?
It looks tedious but, it's weird that `cordova build xxx --release` doesn't do it by itself.

**Comment by lrettig** [comment]
I worked on this for a while and also gave up. I was able to load individual cordova modules such as facebookConnectPlugin via RequireJS by modifying them slightly, but the problem is they all depend on cordova.js and its submodules which I was not able to get working. If I've added the cordova module, though, then it appears that I can refer to the module by name anywhere throughout my code and it's "magically" there. It's messy, and I'd much rather properly `require' these modules and include them in the dependency system, but cordova does not currently make that possible.
