### ISSUE TITLE
What's the best way to implement iCloud with PhoneGap?

### ISSUE THREAD

**Issue by leemarrett** [shazron/phonegap-questions#6]
At the moment I'm using localStorage to store user settings; would be nice to have that stored in iCloud. Is this possible yet?

**Comment by shazron** [comment]
No, this is unlikely to be included in the core API because of a need for cross-platform support. There is a third-party plugin that handles key-value iCloud storage: https://github.com/phonegap/phonegap-plugins/tree/master/iOS/iCloudKV

Other alternatives:
Firebase http://firebase.com (paid, JS sdk)
Amazon DynamoDB http://aws.amazon.com/dynamodb/
OpenKeyval http://openkeyval.org/
Google Drive SDK key value store https://developers.google.com/drive/properties
Elephant (S3-backed): https://github.com/kennethreitz/elephant

**Comment by mgcrea** [comment]
@shazron Isn't window.localStorage already backuped via iCloud (there is a config option about it)?

**Comment by shazron** [comment]
@mcgrea kind-of, for Cordova. Apple doesn't think localStorage is supposed to be backed up in iCloud however :/
